FROM node:18-alpine AS prod
WORKDIR /app
COPY package*.json tsconfig.json  ./
RUN npm install
COPY . .
RUN npm run build

FROM node:18-alpine
WORKDIR /app
COPY --from=prod /app ./
EXPOSE ${API_PORT}
CMD ["npm", "run", "start:prod"]